### ISSUE TITLE
خطای getInstance

### ISSUE THREAD

**Issue by msmousavi4** [hojjat-reyhane/Cafebazaar-IAB-for-Unity#8]
سلام وقتتون بخیر
من از این کتابخونه میخوام استفاده کنم ولی موقعی که میخواد پرداخت رو انجام بدم با این خطا مواجه میشم

2024/09/16 02:49:35.439 11700 11723 Error Unity AndroidJavaException: java.lang.NoSuchMethodError: no static method with name='GetInstance' signature='()Ljava/lang/Object;' in class Lir.cafebazaar.iab.ServiceBillingBazaar;
2024/09/16 02:49:35.439 11700 11723 Error Unity java.lang.NoSuchMethodError: no static method with name='GetInstance' signature='()Ljava/lang/Object;' in class Lir.cafebazaar.iab.ServiceBillingBazaar;
2024/09/16 02:49:35.439 11700 11723 Error Unity 	at com.unity3d.player.ReflectionHelper.getMethodID(Unknown Source:165)
2024/09/16 02:49:35.439 11700 11723 Error Unity 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
2024/09/16 02:49:35.439 11700 11723 Error Unity 	at com.unity3d.player.UnityPlayer.x(Unknown Source:0)
2024/09/16 02:49:35.439 11700 11723 Error Unity 	at com.unity3d.player.UnityPlayer$F$a.handleMessage(Unknown Source:122)
2024/09/16 02:49:35.439 11700 11723 Error Unity 	at android.os.Handler.dispatchMessage(Handler.java:102)
2024/09/16 02:49:35.439 11700 11723 Error Unity 	at android.os.Looper.loopOnce(Looper.java:210)
2024/09/16 02:49:35.439 11700 11723 Error Unity 	at android.os.Looper.loop(Looper.java:299)
2024/09/16 02:49:35.439 11700 11723 Error Unity 	at com.unity3d.player.UnityPlayer$F.run(Unknown Source:24)
2024/09/16 02:49:35.439 11700 11723 Error Unity   at UnityEngine._AndroidJNIHelper.GetMethodID (System.IntPtr jclass, System.String methodName, System.String signature, System.Boolean isStatic) [0x0003c] in <d99e63be59d54d579c6ddccda6cc3939>:0 
2024/09/16 02:49:35.439 11700 11723 Error Unity   at UnityEngine.AndroidJN
چطور میتونم این خطا رو رفع کنم؟

**Comment by msmousavi4** [comment]
سلام مجدد اینو حلش کردم فقط باید پروگارد شما رو جایگزین میکردم..
